# Generated by Django 4.0.3 on 2022-04-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('TA', models.CharField(blank=True, default='19.5', max_length=64, null=True, verbose_name='Среднее значение температуры за 1 минуту, C')),
                ('DP', models.CharField(blank=True, default='8.0', max_length=64, null=True, verbose_name='Точка росы, C')),
                ('WC', models.CharField(blank=True, default='19.5', max_length=64, null=True, verbose_name='Точка росы, C')),
                ('RH', models.CharField(blank=True, default='15', max_length=64, null=True, verbose_name='Относительная влажность, %')),
                ('PA', models.CharField(blank=True, default='744,3', max_length=64, null=True, verbose_name='Атмосферное давление, mm Hg')),
                ('PR', models.CharField(blank=True, default='0.0', max_length=64, null=True, verbose_name='Количество жидких осадков мгновенное значение, мм')),
                ('PR1H', models.CharField(blank=True, default='0.0', max_length=64, null=True, verbose_name='Количество жидких осадков сумма за 1 час, мм')),
                ('PR24H', models.CharField(blank=True, default='5.4', max_length=64, null=True, verbose_name='Количество жидких осадков сумма за сутки, мм')),
                ('SR_1M', models.CharField(blank=True, default='27', max_length=64, null=True, verbose_name='Данные от CMP6 установленного параллельно             относительно поверхности земли (Вт/м²) среднее значение за 1 минуту')),
                ('SR_1D', models.CharField(blank=True, default='26', max_length=64, null=True, verbose_name='Данные от CMP6 установленного параллельно             относительно поверхности земли (Вт/м²) среднее значение за 24 часа')),
                ('SR_45_1M', models.CharField(blank=True, default='27', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов            относительно поверхности земли (Вт/м²) среднее значение за 1 минуту')),
                ('SR_45_1D', models.CharField(blank=True, default='26', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов            относительно поверхности земли (Вт/м²) среднее значение за 24 часа')),
                ('SD_1H', models.CharField(blank=True, default='1190', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно            поверхности земли (Вт/м²) суммарное значение за 1 час')),
                ('SD_1D', models.CharField(blank=True, default='1190', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно            поверхности земли (Вт/м²) суммарное значение за 24 часа')),
                ('SD_45_1H', models.CharField(blank=True, default='1974', max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно            поверхности земли (Вт/м²) суммарное значение за 24 часа')),
            ],
        ),
    ]
