# Generated by Django 4.0.4 on 2022-04-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo_app', '0002_alter_meteomodel_options_alter_meteomodel_dp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteomodel',
            name='SD_45_1D',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно            поверхности земли (Вт/м²) суммарное значение за 24 часа'),
        ),
        migrations.AlterField(
            model_name='meteomodel',
            name='SD_45_1H',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Данные от CMP6 установленного 45 градусов относительно            поверхности земли (Вт/м²) суммарное значение за 1 час'),
        ),
    ]
