# Generated by Django 4.0.4 on 2022-04-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo_app', '0003_meteomodel_sd_45_1d_alter_meteomodel_sd_45_1h'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('WS1AVG', models.CharField(blank=True, default='0.1', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) за 3 сек')),
                ('WD1AVG', models.CharField(blank=True, default='346', max_length=64, null=True, verbose_name='Направление ветра (град) за 3 сек')),
                ('WS1MIN2', models.CharField(blank=True, default='0.1', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) минимальное значение за 2 минуты')),
                ('WS1AVG2', models.CharField(blank=True, default='0.1', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) среднее значение за 2 минуты')),
                ('WS1MAX2', models.CharField(blank=True, default='0.2', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) максимальное значение за 2 минуты')),
                ('WD1MIN2', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) минимальное значение за 2 минуты')),
                ('WD1AVG2', models.CharField(blank=True, default='157', max_length=64, null=True, verbose_name='Направление ветра (град) среднее значение за 2 минуты')),
                ('WD1MAX2', models.CharField(blank=True, default='358', max_length=64, null=True, verbose_name='Направление ветра (град) максимальное значение за 2 минуты')),
                ('WS1MIN10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Cкорость ветра (м/с) минимальное значение за 10 минут')),
                ('WS1AVG10', models.CharField(blank=True, default='0.1', max_length=64, null=True, verbose_name='Скорость ветра (м/с) среднее значение за 10 минут')),
                ('WS1MAX10', models.CharField(blank=True, default='0.2', max_length=64, null=True, verbose_name='Скорость ветра (м/с) максимальное значение за 2 минуты')),
                ('WD1MIN10', models.CharField(blank=True, default='0', max_length=64, null=True, verbose_name='Направление ветра (град) минимальное значение за 10 минут')),
                ('WD1AVG10', models.CharField(blank=True, default='227', max_length=64, null=True, verbose_name='Направление ветра (град) среднее значение за 10 минут')),
                ('WD1MAX10', models.CharField(blank=True, default='358', max_length=64, null=True, verbose_name='Направление ветра (град) максимальное значение за 10 минут')),
            ],
            options={
                'verbose_name': 'Данные с ветряного модуля',
            },
        ),
        migrations.RenameModel(
            old_name='MeteoModel',
            new_name='MeteoData',
        ),
        migrations.AlterModelOptions(
            name='meteodata',
            options={'verbose_name': 'Данные с метеостанции'},
        ),
    ]
