# Generated by Django 4.0.4 on 2022-04-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo_app', '0004_winddata_rename_meteomodel_meteodata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meteodata',
            options={'verbose_name': 'Данные с метеостанции', 'verbose_name_plural': 'Данные с метеостанции'},
        ),
        migrations.AlterModelOptions(
            name='winddata',
            options={'verbose_name': 'Данные с ветряного модуля', 'verbose_name_plural': 'Данные с ветряного модуля'},
        ),
    ]
