# Generated by Django 4.0.4 on 2022-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteo_app', '0006_alter_meteodata_dp_alter_meteodata_pa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='BookTitle', max_length=64, null=True, verbose_name='Заголовок')),
                ('author', models.CharField(blank=True, default='Author', max_length=64, null=True, verbose_name='Автор книги')),
            ],
        ),
    ]
