# Generated by Django 4.0.4 on 2022-04-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo_app', '0008_author_alter_book_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
